name: Test Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run a one-line script
      run: |
        echo "Hey from github actions!"
        echo "This is just a test action without and only prints this message."
